#include <juce_core/juce_core.h>
#include "../Source/Video/VideoDecoder.h"

namespace
{
// Volontairement différent du sample rate audio de la fixture (22050Hz, cf.
// Tests/CMakeLists.txt) pour vérifier que le resampling a bien lieu.
constexpr double testTargetSampleRate = 48000.0;
}

// Vérifie le décodage FFmpeg de bout en bout sur un clip H.264 + audio AAC
// synthétique généré par CMake via `ffmpeg -f lavfi` (voir Tests/CMakeLists.txt).
// Capacité des files largement supérieure au nombre de frames/blocs attendus
// pour que decodeLoop() (appelé de façon synchrone ici, donc sans
// consommateur concurrent) ne bloque jamais sur un push().
class VideoDecoderTests final : public juce::UnitTest
{
public:
    VideoDecoderTests() : juce::UnitTest("VideoDecoder", "Video") {}

    void runTest() override
    {
        beginTest("loadFile succeeds and reports expected dimensions/duration");
        {
            VideoFrameQueue queue(64);
            AudioFrameQueue audioQueue(256);
            VideoDecoder decoder(queue, audioQueue);

            const juce::File fixture(TEST_FIXTURE_MP4_PATH);
            expect(fixture.existsAsFile(), "fixture file should exist (generated by CMake)");

            const bool loaded = decoder.loadFile(fixture, testTargetSampleRate);
            expect(loaded, "loadFile should succeed on a valid H.264 fixture");

            expectEquals(decoder.getWidth(), 320);
            expectEquals(decoder.getHeight(), 240);
            expectWithinAbsoluteError(decoder.getDurationSeconds(), 2.0, 0.2);
            expectWithinAbsoluteError(decoder.getFrameRate(), 25.0, 0.1); // fixture: rate=25
            expectEquals(decoder.getVideoCodecName(), juce::String("H264")); // fixture: -c:v libx264
            expectEquals(decoder.getAudioCodecName(), juce::String("AAC"));  // fixture: -c:a aac
        }

        beginTest("setFrameRate() overrides getFrameRate() independently of getDetectedFrameRate(), "
                  "unloadFile() resets both");
        {
            VideoFrameQueue queue(64);
            AudioFrameQueue audioQueue(256);
            VideoDecoder decoder(queue, audioQueue);

            const juce::File fixture(TEST_FIXTURE_MP4_PATH);
            expect(decoder.loadFile(fixture, testTargetSampleRate));

            const double detected = decoder.getDetectedFrameRate();
            expectWithinAbsoluteError(detected, 25.0, 0.1);
            expectWithinAbsoluteError(decoder.getFrameRate(), detected, 1.0e-9);

            decoder.setFrameRate(30.0);
            expectWithinAbsoluteError(decoder.getFrameRate(), 30.0, 1.0e-9);
            // "Detect" (revenir à la valeur auto-détectée) ne rouvre pas le
            // fichier -- getDetectedFrameRate() doit rester inchangé.
            expectWithinAbsoluteError(decoder.getDetectedFrameRate(), detected, 1.0e-9);

            decoder.setFrameRate(-5.0); // clampé à 1.0, jamais une valeur invalide
            expectWithinAbsoluteError(decoder.getFrameRate(), 1.0, 1.0e-9);

            decoder.unloadFile();
            expectEquals(decoder.getWidth(), 0);
            expectEquals(decoder.getDurationSeconds(), 0.0);
            expectWithinAbsoluteError(decoder.getFrameRate(), 24.0, 1.0e-9);
            expectWithinAbsoluteError(decoder.getDetectedFrameRate(), 24.0, 1.0e-9);
        }

        beginTest("decodeLoop decodes ~50 video frames with monotonically increasing PTS");
        {
            VideoFrameQueue queue(64);
            AudioFrameQueue audioQueue(256);
            VideoDecoder decoder(queue, audioQueue);

            const juce::File fixture(TEST_FIXTURE_MP4_PATH);
            expect(decoder.loadFile(fixture, testTargetSampleRate));

            decoder.decodeLoop([] { return false; }); // synchrone, jusqu'à EOF

            std::vector<double> ptsValues;
            VideoFrameQueue::Frame frame;
            while (queue.pop(frame))
            {
                expectEquals(frame.width, 320);
                expectEquals(frame.height, 240);
                expectEquals((int) frame.rgba.size(), 320 * 240 * 4);
                ptsValues.push_back(frame.ptsSeconds);
            }

            expect(ptsValues.size() >= 45 && ptsValues.size() <= 55,
                   "expected ~50 frames for a 2s @ 25fps clip, got "
                       + juce::String((int) ptsValues.size()));

            for (size_t i = 1; i < ptsValues.size(); ++i)
                expect(ptsValues[i] > ptsValues[i - 1], "PTS should strictly increase frame to frame");

            if (!ptsValues.empty())
            {
                expectWithinAbsoluteError(ptsValues.front(), 0.0, 0.05);
                expectWithinAbsoluteError(ptsValues.back(), 2.0, 0.2);
            }
        }

        beginTest("decodeLoop decodes and resamples audio to the target sample rate");
        {
            VideoFrameQueue queue(64);
            AudioFrameQueue audioQueue(256);
            VideoDecoder decoder(queue, audioQueue);

            const juce::File fixture(TEST_FIXTURE_MP4_PATH);
            expect(decoder.loadFile(fixture, testTargetSampleRate));

            decoder.decodeLoop([] { return false; }); // synchrone, jusqu'à EOF

            int totalFrames = 0;
            double firstPtsSeconds = -1.0;
            double lastPtsSeconds = -1.0;
            AudioFrameQueue::Chunk chunk;

            while (audioQueue.pop(chunk))
            {
                expect(chunk.numFrames > 0, "chunk should carry at least one sample frame");
                expectEquals((int) chunk.interleaved.size(), chunk.numFrames * AudioFrameQueue::numChannels);

                if (firstPtsSeconds < 0.0)
                    firstPtsSeconds = chunk.ptsSeconds;

                lastPtsSeconds = chunk.ptsSeconds;
                totalFrames += chunk.numFrames;
            }

            expect(totalFrames > 0, "fixture has a sine-wave audio track: expected at least one resampled chunk");

            // Resamplé à testTargetSampleRate (48kHz), donc ~2s de contenu
            // doivent correspondre à ~2*48000 échantillons, quelle que soit la
            // taille des blocs individuels issus de swr_convert().
            const double totalSeconds = static_cast<double>(totalFrames) / testTargetSampleRate;
            expectWithinAbsoluteError(totalSeconds, 2.0, 0.2);

            expectWithinAbsoluteError(firstPtsSeconds, 0.0, 0.1);
            expectWithinAbsoluteError(lastPtsSeconds, 2.0, 0.3);
        }

        beginTest("requestSeek rewinds decoding and bumps the frame generation");
        {
            VideoFrameQueue queue(64);
            AudioFrameQueue audioQueue(256);
            VideoDecoder decoder(queue, audioQueue);

            const juce::File fixture(TEST_FIXTURE_MP4_PATH);
            expect(decoder.loadFile(fixture, testTargetSampleRate));

            // Décode jusqu'à l'EOF une première fois (simule une lecture qui
            // va jusqu'au bout, ou tout simplement le play initial), comme le
            // ferait le thread de décodage avant qu'un Stop/Play ne redemande
            // une position antérieure.
            decoder.decodeLoop([] { return false; });

            VideoFrameQueue::Frame frame;
            uint32_t firstPassGeneration = 0;
            int firstPassCount = 0;
            while (queue.pop(frame))
            {
                firstPassGeneration = frame.generation;
                ++firstPassCount;
            }

            expect(firstPassCount > 0, "first pass should have decoded frames");

            // Rejoue exactement ce que fait VideoGLComponent quand SeekPolicy
            // détecte un écart important (ex : Stop ramène la position à 0
            // alors que le décodeur est arrivé en fin de fichier) : requestSeek
            // puis un nouvel appel à decodeLoop() pour l'appliquer.
            decoder.requestSeek(0.0);
            decoder.decodeLoop([] { return false; });

            std::vector<double> secondPassPts;
            uint32_t secondPassGeneration = 0;
            while (queue.pop(frame))
            {
                secondPassPts.push_back(frame.ptsSeconds);
                secondPassGeneration = frame.generation;
            }

            expect(!secondPassPts.empty(), "second pass should decode frames again after seeking back to 0");
            expect(secondPassGeneration > firstPassGeneration,
                   "generation should increase so stale pre-seek frames can be told apart");
            expectWithinAbsoluteError(secondPassPts.front(), 0.0, 0.05);
        }
    }
};

static VideoDecoderTests videoDecoderTests;

int main()
{
    juce::UnitTestRunner runner;
    runner.runAllTests();

    for (int i = 0; i < runner.getNumResults(); ++i)
    {
        const auto* result = runner.getResult(i);
        if (result->failures > 0)
            return 1;
    }

    return 0;
}
